name: Compilación Nocturna

on:
  push:
  schedule:
    - cron: '0 23 * * *'

jobs:
  nightly_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Ejecutar Unit Tests
        run: mvn clean test -DskipTests

      - name: Build WAR
        run: mvn clean package -DskipTests
        
      - uses: actions/upload-artifact@master
        with:
          name: digitalbank-war
          path: ./target/*digitalbank*.war
