name: PR check naming convention

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  scan-pr-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Annotate PR
        uses: tau-github-actions-for-testing/tau-own-action-pull-request@main
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token: ${{ github.token }}
